// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"k80ylgvt73","name":"ReactSample","description":"","endpoint":"https://k80ylgvt73.execute-api.us-east-2.amazonaws.com/Development","region":"us-east-2","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-2:b4aef84c-2125-4eef-aae2-2cab12937b9a',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'whitehousereact-hosting-mobilehub-1257262682',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2am7jvr46ko7v.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-2',
    'aws_dynamodb_table_schemas': [{"tableName":"whitehousereact-mobilehub-1257262682-bbq_restaurants","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-east-2","hashKey":"id"},{"tableName":"whitehousereact-mobilehub-1257262682-bbq_orders","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-east-2","hashKey":"id"},{"tableName":"whitehousereact-mobilehub-1257262682-bbq_menu_item","attributes":[{"name":"restaurant_id","type":"S"},{"name":"id","type":"S"}],"indexes":[],"region":"us-east-2","hashKey":"restaurant_id","rangeKey":"id"}],
    'aws_google_app_permissions': 'email,profile,openid',
    'aws_google_web_app_id': '974294703655-phlk1u4ph2t1sek1hcnddcfpl4q7ocsq.apps.googleusercontent.com',
    'aws_mandatory_sign_in': 'enable',
    'aws_project_id': 'fa467e15-c32e-446e-a20a-4dc030cfe73e',
    'aws_project_name': 'whitehousereact',
    'aws_project_region': 'us-east-2',
    'aws_resource_bucket_name': 'whitehousereact-deployments-mobilehub-1257262682',
    'aws_resource_name_prefix': 'whitehousereact-mobilehub-1257262682',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_2xy0zEYcd',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5hdvkdk1a5l1ggppvu46bmiccr',
}

export default awsmobile;
